=== MN-Alberto/MN-Alberto/112LMSGIProyectoLMSGI/unidad4/02/02.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo,autores,anio)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre,apellido,nacionalidad)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)*>
<!ATTLIST libro idlibro ID #REQUIRED>
<!ATTLIST libro genero CDATA #IMPLIED>
<!ATTLIST libro idioma CDATA "EspaÃ±ol">
<!ATTLIST libro formato (Impreso|Digital) "Impreso">
<!ATTLIST libro ref IDREFS #IMPLIED>

=== MN-Alberto/MN-Alberto/112LMSGIProyectoLMSGI/unidad4/02/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Nombre: Alberto Méndez Núñez
    Descripcion: Información de un libro-->
<!DOCTYPE biblioteca SYSTEM "02.dtd">
<biblioteca>
    <libro idlibro="libro1" genero="novela" ref="libro1">
        <titulo>Puntos para los locos</titulo>
            <autores>
                <autor>
                    <nombre>Angel</nombre>
                        <apellido>Martin</apellido>
                        <nacionalidad>Español</nacionalidad>
                </autor>
            </autores>
        <anio>2024</anio>
    </libro>
    <libro idlibro="libro2" genero="novela" ref="libro2">
        <titulo>Por si las voces vuelven</titulo>
            <autores>
                <autor>
                    <nombre>Angel</nombre>
                        <apellido>Martin</apellido>
                        <nacionalidad>Español</nacionalidad>
                </autor>
            </autores>
        <anio>2020</anio>
    </libro>
</biblioteca>
